# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/redfin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),redfin)

$(call add-radio-file,firmware/bootloader.img)
$(call add-radio-file,firmware/radio.img)

endif
